// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnpkkgygjfxlipqbtybg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducGtrZ3lnamZ4bGlwcWJ0eWJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0MzQ5MjEsImV4cCI6MjA5OTAxMDkyMX0.QzT9d1FAY0W85FbdK3oVKN-TQ6VM5-GuN4ZLzr6y5iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
