// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixbigiyuulijtrhscmvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4YmlnaXl1dWxpanRyaHNjbXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNzY0NTIsImV4cCI6MjA5MDY1MjQ1Mn0.nZWue2eVOgb3kKABlpipqSGdaxC4pK5HFUZ3f3LHYuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
