// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frvclkoljxovzsrnjtlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydmNsa29sanhvdnpzcm5qdGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NjY0MDUsImV4cCI6MjEwMzM0MjQwNX0.ei4rv6Vdobn_8U0U1GMkaoLkFWgT3nKePG6_wIIhP14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
